"""Durable, provider-neutral LLM execution for ARC packages."""

from arc_jobs import (
    ArtifactSourceRef,
    ExecutionFingerprint,
    ResumeReason,
    SemanticKeyDigest,
)

from .api import LLMClient, LLMRunResult, LLMRunView, LLMTaskService
from .errors import (
    AdoptionAuthorizationError,
    AdoptionConflictError,
    ArcLLMError,
    CandidateConflictError,
    CorruptTaskStateError,
    DeliveryState,
    ErrorCode,
    ExecutionMismatchError,
    FailureCategory,
    IdempotencyConflictError,
    InvalidRequestError,
    InvalidSchemaError,
    OutputInvalidError,
    ProviderFailure,
    ResumeInputConflictError,
    ResumeKeyMismatchError,
)
from .identity import AdoptionAuthorization, resume_input_matches
from .interactions import ScopedInteractionLedger
from .outcome import (
    LLMStopped,
    LLMCompleted,
    LLMFailed,
    LLMPaused,
    LLMTaskOutcome,
)
from .providers import (
    IsolationMode,
    NativeResumeHandle,
    ProviderAdapter,
    ProviderCapabilities,
    ProviderDiagnostic,
    ProviderExecution,
    ProviderRegistry,
    ProviderRequest,
    ProviderResumeRequest,
    ProviderTerminalKind,
    ProviderUsage,
    StructuredOutputMode,
    UsageAvailability,
)
from .request import (
    CapabilityPolicy,
    ExecutionLimits,
    InteractionProgress,
    InteractionRequest,
    InteractionResolver,
    InteractionResponse,
    InteractiveJsonOutput,
    JsonOutput,
    LLMExecutionOptions,
    LLMInputArtifact,
    LLMRequest,
    ModelSelection,
    OperationContract,
    OutputContract,
    ProviderGateOptions,
    ResumeAction,
    ResumeInput,
    SessionRef,
    TextOutput,
    decode_request,
    decode_resume_input,
    request_to_document,
    resume_input_to_document,
)

__version__ = "1.0.1"

__all__ = [
    "AdoptionAuthorization",
    "AdoptionAuthorizationError",
    "AdoptionConflictError",
    "ArcLLMError",
    "ArtifactSourceRef",
    "CandidateConflictError",
    "CapabilityPolicy",
    "CorruptTaskStateError",
    "DeliveryState",
    "ErrorCode",
    "ExecutionFingerprint",
    "ExecutionLimits",
    "ExecutionMismatchError",
    "FailureCategory",
    "IdempotencyConflictError",
    "InteractionProgress",
    "InteractionRequest",
    "InteractionResolver",
    "InteractionResponse",
    "InteractiveJsonOutput",
    "InvalidRequestError",
    "InvalidSchemaError",
    "JsonOutput",
    "LLMStopped",
    "LLMClient",
    "LLMCompleted",
    "LLMExecutionOptions",
    "LLMInputArtifact",
    "LLMFailed",
    "LLMPaused",
    "LLMRequest",
    "LLMRunResult",
    "LLMRunView",
    "LLMTaskOutcome",
    "LLMTaskService",
    "ModelSelection",
    "NativeResumeHandle",
    "OperationContract",
    "OutputContract",
    "OutputInvalidError",
    "ProviderAdapter",
    "ProviderCapabilities",
    "ProviderDiagnostic",
    "ProviderExecution",
    "ProviderFailure",
    "ProviderGateOptions",
    "ProviderRegistry",
    "ProviderRequest",
    "ProviderResumeRequest",
    "ProviderTerminalKind",
    "ProviderUsage",
    "ResumeAction",
    "ResumeInput",
    "ResumeInputConflictError",
    "ResumeKeyMismatchError",
    "ResumeReason",
    "ScopedInteractionLedger",
    "SemanticKeyDigest",
    "SessionRef",
    "StructuredOutputMode",
    "TextOutput",
    "UsageAvailability",
    "IsolationMode",
    "decode_request",
    "decode_resume_input",
    "request_to_document",
    "resume_input_to_document",
    "resume_input_matches",
]
