"""Durable, protocol-neutral run kernel for ARC packages."""

from .cancellation import CancellationToken
from .artifacts import (
    decode_artifact_digest,
    decode_artifact_ref,
    encode_artifact_digest,
    encode_artifact_ref,
)
from .cli import main as run_control_main
from .contracts import StateContract
from .effects import EffectJournal, EffectRecoveryPolicy
from .engine import RunContext, RunEngine, RunHandler, RunRepository
from .errors import (
    ArcJobsError,
    ArtifactConflictError,
    CancelledError,
    CorruptStateError,
    IdempotencyConflictError,
    InvalidRunIdError,
    InvalidStateError,
    InvalidTransitionError,
    ResumeInputConflictError,
    ResumeMismatchError,
    RevisionConflictError,
    RunBusyError,
    RunNotFoundError,
    StateConflictError,
    UnsafeEffectRecoveryError,
    UnsupportedSchemaError,
)
from .events import EventWriter
from .lease_pool import BoundedLease, BoundedLeasePool
from .identity import (
    canonical_json_bytes,
    semantic_key,
    validate_artifact_id,
    validate_simple_id,
)
from .models import (
    ArtifactDigest,
    ArtifactRef,
    ArtifactSourceRef,
    Awaiting,
    CancelRequest,
    EffectRecord,
    EffectRequestDigest,
    EffectStage,
    ExecutionFingerprint,
    ExecutionSlice,
    Failed,
    FailureMode,
    GroupExecutionResult,
    GroupResult,
    GroupUnitView,
    GroupView,
    JsonValue,
    Paused,
    RecoveryDecision,
    ResumeReason,
    RunError,
    RunOutcome,
    RunSnapshot,
    RunSpec,
    RunStatus,
    RunView,
    SemanticKeyDigest,
    Succeeded,
    UnitResult,
    ValidationIssue,
    ValidationReport,
    VerifiedArtifact,
    WorkUnit,
)
from .protocol import (
    CommandArtifact,
    CommandError,
    CommandResult,
    CommandRun,
    CommandStatus,
    CommandWarning,
    ProgressEvent,
    ResumeDescriptor,
    command_result_from_snapshot,
    command_result_json,
    decode_command_result,
    decode_progress_event,
    encode_command_result,
    encode_progress_event,
    resume_from_awaiting,
    snapshot_data,
    validate_command_result,
)
from .progress import validate_progress_data
from .storage import AtomicStateStore, ImmutableArtifactStore

__version__ = "1.0.1"

__all__ = [
    "ArcJobsError",
    "ArtifactConflictError",
    "ArtifactDigest",
    "ArtifactRef",
    "ArtifactSourceRef",
    "AtomicStateStore",
    "Awaiting",
    "BoundedLease",
    "BoundedLeasePool",
    "CancellationToken",
    "CancelledError",
    "CommandArtifact",
    "CommandError",
    "CommandResult",
    "CommandRun",
    "CommandStatus",
    "CommandWarning",
    "CorruptStateError",
    "EffectJournal",
    "EffectRecord",
    "EffectRecoveryPolicy",
    "EffectRequestDigest",
    "EffectStage",
    "EventWriter",
    "ExecutionFingerprint",
    "ExecutionSlice",
    "Failed",
    "FailureMode",
    "GroupExecutionResult",
    "GroupResult",
    "GroupUnitView",
    "GroupView",
    "IdempotencyConflictError",
    "ImmutableArtifactStore",
    "InvalidRunIdError",
    "InvalidStateError",
    "InvalidTransitionError",
    "JsonValue",
    "Paused",
    "ProgressEvent",
    "RecoveryDecision",
    "ResumeDescriptor",
    "ResumeInputConflictError",
    "ResumeMismatchError",
    "ResumeReason",
    "RevisionConflictError",
    "RunBusyError",
    "RunContext",
    "RunEngine",
    "RunError",
    "RunHandler",
    "RunNotFoundError",
    "RunOutcome",
    "RunRepository",
    "RunSnapshot",
    "RunSpec",
    "RunStatus",
    "RunView",
    "SemanticKeyDigest",
    "StateConflictError",
    "StateContract",
    "Succeeded",
    "UnitResult",
    "UnsafeEffectRecoveryError",
    "UnsupportedSchemaError",
    "ValidationIssue",
    "ValidationReport",
    "VerifiedArtifact",
    "WorkUnit",
    "canonical_json_bytes",
    "command_result_from_snapshot",
    "command_result_json",
    "decode_command_result",
    "decode_progress_event",
    "decode_artifact_digest",
    "decode_artifact_ref",
    "encode_artifact_digest",
    "encode_artifact_ref",
    "encode_command_result",
    "encode_progress_event",
    "resume_from_awaiting",
    "run_control_main",
    "semantic_key",
    "snapshot_data",
    "validate_artifact_id",
    "validate_command_result",
    "validate_progress_data",
    "validate_simple_id",
]
